version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: lawfirm_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lawfirm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
